import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Copy the NEXT_PUBLIC_* variables from the repo-root .env into apps/web.
 *
 * Next.js reads .env files from ITS OWN project directory and does not walk
 * up. In this monorepo that means `next build`, which runs with cwd
 * apps/web, never sees the .env at the root. The API gets away with it only
 * because load-env.ts searches upward by hand.
 *
 * The consequence was not a helpful error. `process.env.NEXT_PUBLIC_API_URL`
 * simply inlined as undefined, the code fell back to http://localhost:4000,
 * and the deployed site shipped JavaScript that called a port on the
 * visitor's own machine. Over HTTPS that is mixed content, so the browser
 * blocked every request and showed "not secure" while reporting the
 * certificate as valid. It took a long time to find because every individual
 * piece looked correct.
 *
 * Only NEXT_PUBLIC_* is copied, deliberately. Those are public by definition
 * and Next inlines them into the browser bundle. Copying the whole file would
 * put ANTHROPIC_API_KEY inside a Next build for no reason.
 */
const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const source = join(root, '.env');
const target = join(root, 'apps', 'web', '.env.production');

if (!existsSync(source)) {
  console.log('[sync-web-env] no root .env, nothing to copy');
  process.exit(0);
}

const lines = readFileSync(source, 'utf8')
  .split('\n')
  .filter((line) => /^\s*NEXT_PUBLIC_[A-Z0-9_]+\s*=/.test(line));

if (lines.length === 0) {
  console.log('[sync-web-env] root .env defines no NEXT_PUBLIC_* variables');
  process.exit(0);
}

writeFileSync(
  target,
  '# Generated by scripts/sync-web-env.mjs from the repo-root .env.\n' +
    '# Do not edit. Next.js cannot read the root file itself; see that script.\n' +
    `${lines.join('\n')}\n`,
  'utf8',
);

console.log(
  `[sync-web-env] wrote ${lines.length} variable(s) to apps/web/.env.production`,
);
for (const line of lines) console.log(`  ${line.split('=')[0].trim()}`);
